name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  testeo-y-build:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar el c√≥digo, we
        uses: actions/checkout@v4

      - name: Poner Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar chingaderas (dependencias)
        run: npm ci

      - name: Checar que no escriban con las patas (Lint)
        run: npm run lint

      - name: Checar tipado estricto
        run: npx tsc --noEmit

      - name: Generar Prisma
        run: npx prisma generate
        env:
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"

      - name: Calar el Build
        run: npm run build
        env:
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    needs: testeo-y-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Copiar archivos al servidor
        run: rsync -av --delete . /home/fabianshady/Projects/agenda/app_futbol_public/

      - name: Deploy with Docker Compose
        working-directory: /home/fabianshady/Projects/agenda/compose
        run: docker compose --profile football-apps up -d --build  