name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  testeo-y-build:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar el c√≥digo, we
        uses: actions/checkout@v4

      - name: Poner Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar chingaderas (dependencias)
        run: npm ci

      - name: Checar que no escriban con las patas (Lint)
        run: npm run lint

      - name: Checar tipado estricto
        run: npx tsc --noEmit

      - name: Generar Prisma
        run: npx prisma generate
        env:
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"

      - name: Calar el Build
        run: npm run build
        env:
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"

  docker-build-y-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: testeo-y-build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Loguearse en GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Armar la imagen y treparla a GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/app_futbol_public:latest
            ghcr.io/${{ github.repository_owner }}/app_futbol_public:${{ github.sha }}

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    needs: docker-build-y-push
    steps:
      - name: Bajar la nueva imagen y reiniciar el desmadre
        working-directory: /home/fabianshady/Projects/agenda/compose
        run: |
          docker compose --profile football-apps pull app_futbol_public
          docker compose --profile football-apps up -d